defaults: &defaults
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *defaults
  encoding: UTF8

test:
  <<: *defaults
  encoding: UTF8

production:
  <<: *defaults

staging:
  <<: *defaults

stagingnxt:
  <<: *defaults

sit:
  <<: *defaults
