development:
  secret_key_base: 'dsfguvhadognljvadnouadgbaidkbhgvadfkbjv'

test:
  secret_key_base: 'sadviuregooniqougvnbosbaovneufmakivbdio'

production;:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
